# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72ba66b0c8952a30ad7cdac71ef9facd"
application_url = "https://waste-groundwater-get-crop.trycloudflare.com"
embedded = true
name = "Bustem_Polaris"
handle = "bustem_polaris"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://waste-groundwater-get-crop.trycloudflare.com/auth/callback",
  "https://waste-groundwater-get-crop.trycloudflare.com/auth/shopify/callback",
  "https://waste-groundwater-get-crop.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "bustem-polaris.myshopify.com"
automatically_update_urls_on_dev = true
